resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: ./build.ps1
  displayName: 'PowerShell Script'
- task: CopyFiles@2
  displayName: 'Copy Files to $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*
     !*.md|*.yml|.git/**/*|build.ps1
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop